// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzeTLKt4kl0voREa8XjLtRRjzDg_Z6xGE',
    appId: '1:793859769885:web:e9d664c4d7a023b77f28f4',
    messagingSenderId: '793859769885',
    projectId: 'fooddelivery-d8857',
    authDomain: 'fooddelivery-d8857.firebaseapp.com',
    storageBucket: 'fooddelivery-d8857.appspot.com',
    measurementId: 'G-3PRYCYM1Y9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMWcVGNo790C--exCYPLofnqRrz3FbGLE',
    appId: '1:793859769885:android:6dd2a3c4795785097f28f4',
    messagingSenderId: '793859769885',
    projectId: 'fooddelivery-d8857',
    storageBucket: 'fooddelivery-d8857.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPRkxymwrQ3YKE-DXvbwjklK-5WXB_1vg',
    appId: '1:793859769885:ios:44f1323eba80f0ee7f28f4',
    messagingSenderId: '793859769885',
    projectId: 'fooddelivery-d8857',
    storageBucket: 'fooddelivery-d8857.appspot.com',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPRkxymwrQ3YKE-DXvbwjklK-5WXB_1vg',
    appId: '1:793859769885:ios:44f1323eba80f0ee7f28f4',
    messagingSenderId: '793859769885',
    projectId: 'fooddelivery-d8857',
    storageBucket: 'fooddelivery-d8857.appspot.com',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzeTLKt4kl0voREa8XjLtRRjzDg_Z6xGE',
    appId: '1:793859769885:web:a66520e166982a5e7f28f4',
    messagingSenderId: '793859769885',
    projectId: 'fooddelivery-d8857',
    authDomain: 'fooddelivery-d8857.firebaseapp.com',
    storageBucket: 'fooddelivery-d8857.appspot.com',
    measurementId: 'G-176MS0K5VZ',
  );
}
